sudo: required
services:
  - docker

before_install:
  - docker build -t meetarun/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run meetarun/react-test npm test -- --coverage

after_success:
  - docker build -t meetarun/multi-client ./client
  - docker build -t meetarun/multi-nginx ./nginx
  - docker build -t meetarun/multi-server ./server
  - docker build -t meetarun/multi-worker ./worker

  # login to docker cli
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  
  # take images and push them to docker hub
  - docker push meetarun/multi-client
  - docker push meetarun/multi-nginx
  - docker push meetarun/multi-server
  - docker push meetarun/multi-worker